// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVn0BW-Ac8zstR0LYvO0JVPPrRpMKdU4E',
    appId: '1:234441083587:web:cf47e221e5fd241a3ab076',
    messagingSenderId: '234441083587',
    projectId: 'print-f3170',
    authDomain: 'print-f3170.firebaseapp.com',
    storageBucket: 'print-f3170.appspot.com',
    measurementId: 'G-RPENXC762T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAveXm2-Y0j6Hkjmcsv1tY0YQ37tTtrYzY',
    appId: '1:234441083587:android:9d4cc00b150f2cde3ab076',
    messagingSenderId: '234441083587',
    projectId: 'print-f3170',
    storageBucket: 'print-f3170.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqgUucUFrTN3uO_6Hc9uN36fVVvPP1ZEc',
    appId: '1:234441083587:ios:c04f8462e86383553ab076',
    messagingSenderId: '234441083587',
    projectId: 'print-f3170',
    storageBucket: 'print-f3170.appspot.com',
    iosClientId: '234441083587-uctff68afsdec7bbbcdtgd3cansj4j75.apps.googleusercontent.com',
    iosBundleId: 'com.example.printsecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqgUucUFrTN3uO_6Hc9uN36fVVvPP1ZEc',
    appId: '1:234441083587:ios:c04f8462e86383553ab076',
    messagingSenderId: '234441083587',
    projectId: 'print-f3170',
    storageBucket: 'print-f3170.appspot.com',
    iosClientId: '234441083587-uctff68afsdec7bbbcdtgd3cansj4j75.apps.googleusercontent.com',
    iosBundleId: 'com.example.printsecure',
  );
}
